name: Build Xamarin.Android app

on: [push]

jobs:
  build-android-app:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set default Xamarin SDK versions
      run: |
        $VM_ASSETS/select-xamarin-sdk-v2.sh

    - name: Setup .NET Core SDK 5.0.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    - name: Install dependencies
      run: nuget restore EncounterMeApp.sln

    - name: Build
      run: msbuild EncounterMeApp/EncounterMeApp.Android/EncounterMeApp.Android.csproj /p:Configuration=Debug
