name: Build Xamarin.Android app on windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-android-app-windows:

    runs-on: windows-latest

    steps:
    
    - name: Setup .NET Core SDK 5.0.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    - name: Install dependencies
      run: nuget restore EncounterMeApp.sln

    - name: Build
      run: msbuild /p:Configuration=Debug
